### ISSUE TITLE
booking

### ISSUE THREAD

**Issue by RodDeacon** [davidkislyak/tickettiger#14]
after choosing your seat, the program asks you if you would like to book now. Choosing N restarts the program.

Should it quit the program instead?

**Comment by davidkislyak** [comment]
As we have more than the booking function in our program, I think we should let the user still access the other aspects of our program.

**Comment by LiumuYeAlex** [comment]
right is like the option enter 0 to exit, is not refer to program, but the function request ticket, is like the "back button"
