### ISSUE TITLE
requestTicket() booking error?

### ISSUE THREAD

**Issue by RodDeacon** [davidkislyak/tickettiger#16]
in requestTicket if Nseat is 0 (no seats selected) then it doesn’t quit the program, it relaunches menuChoice() function.

Should this display a message saying "No seats selected" Then end the program?

**Comment by LiumuYeAlex** [comment]
entering 0 is exit from choice number 3 {ticket request option) so should go back to the main menu

**Comment by davidkislyak** [comment]
I also agree that we should keep how it currently is and place the user back the menu.
